[package]
name = "rbook-utils"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
html2md = "0.2"
kuchiki = "0.8"
rbook = { path = "../../rbook" }
urlencoding = "2.1"
walkdir = "2.5"
regex = "1.11"
once_cell = "1.20"
